version: "3"
name: song-sync
services:
  backend-service:
    build:
      context: ./song_sync_backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=song_sync
      - DB_NAME=song_db
    networks:
      - external

  frontend-service:
    build:
      context: ./song_sync_frontend 
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - external

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    networks:
      - external
    volumes:
      - /var/persistent_storage/pg_data:/var/lib/postgresql/data
      - /var/persistent_storage/transfer:/var/transfer:rw
    environment:
      - POSTGRES_PASSWORD=song_sync
      - POSTGRES_USER=postgres
      - POSTGRES_DB=song_db




networks:
  external:
    name: docker-bridge-network
    external: true
