name: song-sync
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - /var/persistent_storage/pg_data:/var/lib/postgresql/data
      - /var/persistent_storage/transfer:/var/transfer:rw
    environment:
      - POSTGRES_PASSWORD=song_sync
      - POSTGRES_USER=postgres
      - POSTGRES_DB=song_db



